### ISSUE TITLE
Ferrum::Network::Exchange doesn't support #url

### ISSUE THREAD

**Issue by nmagedman** [route/ferrum#32]
I have a test helper function that calls
`page.driver.network_traffic.select { |request| request.url =~ /foo/ }`

This code used to work but is broken with Cuprite 0.8 and the advent of `Ferrum::Network::Exchange`.   Is this an intentional change of the API?

Thank you for your help!

**Comment by route** [comment]
Hey Noach, sorry for inconvenience but this is an intended change, it was done in order to combine all 3 entities (request, response, error) into one object to simplify work with it. As it's still pre 1.0 there can be backwards incompatible API changes. You can rewrite it as `page.driver.network_traffic.select { |e| e.request.url =~ /foo/ }`

**Comment by route** [comment]
Feel free to give feedback about API
